# Generated by Django 5.2.4 on 2025-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('casino', models.CharField(max_length=100)),
                ('confirmado', models.BooleanField(default=False)),
                ('comida', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
