# Generated by Django 5.2.4 on 2025-09-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_casino_comida_alter_registro_casino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='documento',
            field=models.CharField(max_length=50),
        ),
    ]
