# Generated by Django 5.2.4 on 2025-09-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_registro_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='comida',
        ),
        migrations.AddField(
            model_name='registro',
            name='comida',
            field=models.ManyToManyField(to='registro.comida'),
        ),
    ]
