# Generated by Django 5.2.4 on 2025-09-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_registro_comida_registro_comida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='comida',
        ),
        migrations.AddField(
            model_name='registro',
            name='comida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='registro.comida'),
        ),
    ]
