# Generated by Django 5.2.4 on 2025-09-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_remove_registro_comida_registro_comida'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
