# Generated by Django 5.2.4 on 2026-05-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0006_comida_habilitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='registro.casino')),
            ],
            options={
                'verbose_name': 'Dispositivo Biométrico',
                'verbose_name_plural': 'Dispositivos Biométricos',
            },
        ),
        migrations.CreateModel(
            name='LogBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_id_dispositivo', models.PositiveIntegerField(db_index=True)),
                ('timestamp_dispositivo', models.DateTimeField(db_index=True)),
                ('tipo_verificacion', models.PositiveSmallIntegerField(default=1)),
                ('payload_raw', models.JSONField(blank=True, default=dict)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='biometrico.dispositivobiometrico')),
            ],
            options={
                'verbose_name': 'Log Biométrico',
                'verbose_name_plural': 'Logs Biométricos',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha', models.DateField(db_index=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='registro.casino')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='registro.comida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('log_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencia', to='biometrico.logbiometrico')),
            ],
            options={
                'verbose_name': 'Asistencia a Comida',
                'verbose_name_plural': 'Asistencias a Comidas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user_id_dispositivo', models.PositiveIntegerField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='biometrico.dispositivobiometrico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles_biometricos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Biométrico',
                'verbose_name_plural': 'Usuarios Biométricos',
            },
        ),
        migrations.AddIndex(
            model_name='logbiometrico',
            index=models.Index(fields=['dispositivo', 'timestamp_dispositivo'], name='biometrico__disposi_5e817c_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenciacomida',
            index=models.Index(fields=['fecha', 'comida'], name='biometrico__fecha_8e3bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenciacomida',
            index=models.Index(fields=['casino', 'fecha'], name='biometrico__casino__063172_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenciacomida',
            unique_together={('usuario', 'comida', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariobiometrico',
            unique_together={('dispositivo', 'user_id_dispositivo')},
        ),
    ]
