# Generated by Django 5.2.4 on 2025-07-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_casino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_usuarioBasico',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
